version: '2.3'
services:
  server:
    build:
      context: ./
      dockerfile: Dockerfiles/server/Dockerfile
    container_name: text-anlyser-server
    restart: unless-stopped
    ports:
      - '3005:3005'
    links:
      - corenlp
  corenlp:
    build:
      context: ./
      dockerfile: Dockerfiles/corenlp/Dockerfile
    container_name: corenlp
    restart: unless-stopped
    ports:
      - '9000:9000'


      